# Generated by Django 5.2.6 on 2025-09-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Salón Social, Piscina Principal', max_length=100, verbose_name='Nombre del Área')),
                ('area_type', models.CharField(choices=[('salon_social', 'Salón Social'), ('piscina', 'Piscina'), ('gimnasio', 'Gimnasio'), ('parque_jardin', 'Parque/Jardín'), ('cancha_deportiva', 'Cancha Deportiva'), ('zona_bbq', 'Zona BBQ'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('location', models.CharField(help_text='Ej: Primer piso, Torre A', max_length=100, verbose_name='Ubicación')),
                ('capacity', models.PositiveIntegerField(help_text='Número máximo de personas', verbose_name='Capacidad (personas)')),
                ('start_time', models.TimeField(help_text='Hora de apertura del área', verbose_name='Hora de Inicio')),
                ('end_time', models.TimeField(help_text='Hora de cierre del área', verbose_name='Hora de Fin')),
                ('requires_reservation', models.BooleanField(default=True, verbose_name='Requiere reserva previa')),
                ('usage_rules', models.TextField(help_text='Reglas y normas para el uso del área común', verbose_name='Reglas de Uso')),
                ('description', models.TextField(blank=True, help_text='Descripción adicional del área común', verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, help_text='Si el área está disponible para uso', verbose_name='Activa')),
                ('is_maintenance', models.BooleanField(default=False, help_text='Si el área está en mantenimiento', verbose_name='En Mantenimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Área Común',
                'verbose_name_plural': 'Áreas Comunes',
                'db_table': 'common_areas',
                'ordering': ['name'],
            },
        ),
    ]
