# Generated by Django 5.2.6 on 2025-09-30 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common_areas', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('document_id', models.CharField(blank=True, max_length=50, verbose_name='Cédula/CI')),
                ('document_photo_front', models.FileField(blank=True, null=True, upload_to='visitors/documents/', verbose_name='Foto Anverso CI')),
                ('document_photo_back', models.FileField(blank=True, null=True, upload_to='visitors/documents/', verbose_name='Foto Reverso CI')),
                ('reason', models.CharField(choices=[('visita_familiar', 'Visita Familiar'), ('delivery', 'Delivery'), ('trabajo_servicio', 'Trabajo/Servicio'), ('servicio_tecnico', 'Servicio Técnico'), ('otro', 'Otro')], default='visita_familiar', max_length=50, verbose_name='Motivo de Visita')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('check_in_time', models.DateTimeField(auto_now_add=True, verbose_name='Hora de Ingreso')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Salida')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el visitante sigue dentro del condominio', verbose_name='Activo')),
                ('common_area_to_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_visitors', to='common_areas.commonarea', verbose_name='Área Común a Visitar')),
                ('property_to_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_visitors', to='properties.property', verbose_name='Casa/Propiedad a Visitar')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_visitors', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Registro de Visitante',
                'verbose_name_plural': 'Registros de Visitantes',
                'db_table': 'visitor_logs',
                'ordering': ['-check_in_time'],
            },
        ),
        migrations.CreateModel(
            name='VisitVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, verbose_name='Placa')),
                ('color', models.CharField(blank=True, max_length=30, verbose_name='Color')),
                ('model', models.CharField(blank=True, max_length=50, verbose_name='Modelo')),
                ('vehicle_type', models.CharField(choices=[('light', 'Vehículo Liviano'), ('heavy', 'Vehículo Pesado'), ('motorcycle', 'Motocicleta')], default='light', max_length=20, verbose_name='Tipo de Vehículo')),
                ('visitor_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='visitor_control.visitorlog', verbose_name='Visita Asociada')),
            ],
            options={
                'verbose_name': 'Vehículo de Visita',
                'verbose_name_plural': 'Vehículos de Visita',
                'db_table': 'visit_vehicles',
            },
        ),
    ]
