# Generated by Django 5.2.6 on 2025-09-30 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntrusionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(help_text='Ej: Intruso detectado, Persona no reconocida.', max_length=255, verbose_name='Mensaje de Alerta')),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, help_text='Nivel de confianza de la detección si aplica.', max_digits=5, null=True, verbose_name='Confianza (%)')),
                ('detection_time', models.DateTimeField(auto_now_add=True, verbose_name='Hora de Detección')),
                ('camera_identifier', models.CharField(blank=True, help_text='Ej: Camara 1, Acceso Principal', max_length=50, verbose_name='Cámara/Punto de Detección')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Resuelto')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_intrusions', to=settings.AUTH_USER_MODEL, verbose_name='Resuelto por')),
            ],
            options={
                'verbose_name': 'Registro de Intrusión',
                'verbose_name_plural': 'Registros de Intrusos',
                'db_table': 'intrusion_logs',
                'ordering': ['-detection_time'],
            },
        ),
    ]
