# Generated by Django 5.2.6 on 2025-12-18 09:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('type', models.CharField(choices=[('income', 'Ingreso'), ('expense', 'Egreso')], max_length=20, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Categoría de Pago',
                'verbose_name_plural': 'Categorías de Pago',
                'db_table': 'payment_categories',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'Cobro (Ingreso)'), ('expense', 'Pago (Egreso)')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('concept', models.CharField(help_text='Título breve del movimiento', max_length=150, verbose_name='Concepto')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('cancelled', 'Anulado')], default='pending', max_length=20, verbose_name='Estado')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Emisión/Registro')),
                ('due_date', models.DateField(blank=True, help_text='Solo para cobros', null=True, verbose_name='Fecha de Vencimiento')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago Real')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado (Timestamp)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado (Timestamp)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='billing.paymentcategory', verbose_name='Categoría')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='properties.property', verbose_name='Propiedad/Unidad')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'db_table': 'transactions',
                'ordering': ['-issue_date', '-created_at'],
                'indexes': [models.Index(fields=['transaction_type', 'status'], name='transaction_transac_9f5934_idx'), models.Index(fields=['issue_date'], name='transaction_issue_d_aa60e9_idx')],
            },
        ),
    ]
