# Generated by Django 5.2.6 on 2025-09-28 17:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(help_text='Ej: 101, A-205', max_length=50, unique=True, verbose_name='Número de Casa')),
                ('block', models.CharField(help_text='Ej: A, B, Torre 1', max_length=50, verbose_name='Bloque')),
                ('floor', models.CharField(blank=True, help_text='Ej: 1, 2, 3', max_length=10, verbose_name='Piso')),
                ('area_m2', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Área (m²)')),
                ('bedrooms', models.PositiveIntegerField(default=1, verbose_name='Habitaciones')),
                ('bathrooms', models.PositiveIntegerField(default=1, verbose_name='Baños')),
                ('parking_spaces', models.PositiveIntegerField(default=0, verbose_name='Espacios de Parqueo')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('occupied', 'Ocupada'), ('maintenance', 'En Mantenimiento'), ('reserved', 'Reservada')], default='available', max_length=20, verbose_name='Estado')),
                ('description', models.TextField(blank=True, help_text='Descripción adicional de la propiedad', verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('owner', models.ForeignKey(blank=True, help_text='Propietario actual de la propiedad', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'db_table': 'properties',
                'ordering': ['block', 'house_number'],
            },
        ),
        migrations.CreateModel(
            name='PropertyResident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(help_text='Ej: Familiar, Inquilino, etc.', max_length=50, verbose_name='Relación')),
                ('is_primary_resident', models.BooleanField(default=False, verbose_name='Residente Principal')),
                ('move_in_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Ingreso')),
                ('move_out_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Salida')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='properties.property')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resided_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Residente de Propiedad',
                'verbose_name_plural': 'Residentes de Propiedades',
                'db_table': 'property_residents',
                'unique_together': {('property', 'resident')},
            },
        ),
    ]
