# Generated by Django 5.2.6 on 2025-09-29 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Comunicado')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('communication_type', models.CharField(choices=[('urgent', 'Urgente'), ('general', 'Anuncio General'), ('maintenance', 'Mantenimiento'), ('event', 'Evento')], default='general', max_length=20, verbose_name='Tipo de Comunicado')),
                ('priority', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10, verbose_name='Prioridad')),
                ('target_audience', models.CharField(choices=[('all_residents', 'Todos los Residentes'), ('owners_only', 'Solo Propietarios'), ('tenants_only', 'Solo Inquilinos')], default='all_residents', max_length=20, verbose_name='Dirigido a')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='communications/attachments/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Comunicado',
                'verbose_name_plural': 'Comunicados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_by', to='communications.communication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lectura de Comunicado',
                'verbose_name_plural': 'Lecturas de Comunicados',
                'unique_together': {('communication', 'user')},
            },
        ),
    ]
