# Generated by Django 5.2.6 on 2025-09-28 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(help_text='Ej: ABC123', max_length=20, unique=True, verbose_name='Placa')),
                ('brand', models.CharField(help_text='Ej: Toyota, Chevrolet', max_length=50, verbose_name='Marca')),
                ('model', models.CharField(help_text='Ej: Corolla, Spark', max_length=50, verbose_name='Modelo')),
                ('year', models.PositiveIntegerField(help_text='Ej: 2020', verbose_name='Año')),
                ('color', models.CharField(help_text='Ej: Blanco, Negro, Azul', max_length=30, verbose_name='Color')),
                ('vehicle_type', models.CharField(choices=[('light', 'Vehículo Ligero'), ('heavy', 'Vehículo Pesado'), ('motorcycle', 'Motocicleta')], max_length=20, verbose_name='Tipo de Vehículo')),
                ('parking_space', models.CharField(blank=True, help_text='Ej: P-15, Sótano A-23', max_length=50, verbose_name='Espacio de Parqueo')),
                ('observations', models.TextField(blank=True, help_text='Observaciones adicionales del vehículo', verbose_name='Observaciones')),
                ('is_active', models.BooleanField(default=True, help_text='Si el vehículo está activo en el sistema', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('owner', models.ForeignKey(help_text='Residente propietario del vehículo', on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'vehicles',
                'ordering': ['license_plate'],
            },
        ),
    ]
