# Generated by Django 5.2.6 on 2025-09-28 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('admin', 'Administrador'), ('security', 'Seguridad'), ('camera', 'Cámara'), ('resident', 'Residente')], max_length=20, verbose_name='Tipo de usuario')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='ResidentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_type', models.CharField(choices=[('owner', 'Propietario'), ('family', 'Familiar'), ('tenant', 'Inquilino')], max_length=20, verbose_name='Tipo de residente')),
                ('birth_date', models.DateField(verbose_name='Fecha de nacimiento')),
                ('face_photo', models.ImageField(blank=True, null=True, upload_to='resident_photos/', verbose_name='Foto del rostro')),
                ('house_identifier', models.CharField(blank=True, help_text='Por ahora solo texto, después será FK', max_length=50, verbose_name='Identificador de casa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resident_info', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Perfil de Residente',
                'verbose_name_plural': 'Perfiles de Residentes',
                'db_table': 'resident_profiles',
            },
        ),
    ]
