# Generated by Django 5.2.6 on 2025-09-29 19:57

import apps.users.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentprofile',
            name='face_photo',
            field=models.ImageField(blank=True, null=True, storage=apps.users.storage.SupabaseStorage(), upload_to='', verbose_name='Foto del rostro'),
        ),
    ]
