# Generated by Django 5.2.6 on 2025-09-30 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_time', models.DateTimeField(auto_now_add=True, verbose_name='Hora de Acceso')),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Confianza (%)')),
                ('is_authorized', models.BooleanField(default=False, verbose_name='Autorizado')),
                ('main_message', models.CharField(max_length=100, verbose_name='Mensaje Principal')),
                ('detail_message', models.CharField(blank=True, max_length=255, verbose_name='Mensaje de Detalle')),
                ('access_point', models.CharField(blank=True, max_length=50, verbose_name='Punto de Acceso (Ej. Puerta Principal)')),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to=settings.AUTH_USER_MODEL, verbose_name='Residente (si reconocido)')),
            ],
            options={
                'verbose_name': 'Registro de Acceso',
                'verbose_name_plural': 'Registros de Acceso',
                'db_table': 'access_logs',
                'ordering': ['-access_time'],
            },
        ),
    ]
